site_name: Computer Science
site_url: https://qfwuecrk.github.io
theme:
  name: material
  language: zh
  palette:    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
  icon:
    annotation: material/arrow-right-circle
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      pygments_lang_class: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - attr_list
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
nav:
  - 简介: 
    - 主页: index.md
  - 计算机系统概论:
    - 计算机系统概论: CS/index.md
  - C:
    - C Programming Language: C/index.md
  - CPP:
    - Cpp Programming Language: CPP/index.md
  - 数据结构:
    - 数据结构: DataStructures/index.md
  - 算法:
    - 算法: Algorithms/index.md
  - Unix:
    - Unix: Unix/index.md
  - Linux:
    - Linux: Linux/index.md
  - FreeBSD:
    - FreeBSD: FreeBSD/index.md
  - Python:
    - Python: Python/index.md
  - OpenGL:
    - OpenGL: OpenGL/index.md
  - Math:
    - Math: Math/index.md
  - English:
    - English: English/index.md
