site_name: Computer Science
site_url: https://qfwuecrk.github.io
theme:
  name: material
  language: zh
  palette:    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
  icon:
    annotation: material/arrow-right-circle
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      pygments_lang_class: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - attr_list
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
nav:
  - 简介: 
    - 主页: index.md
  - 高等数学:
    - 高等数学: FurtherMathematics/index.md
  - 计算机系统概论:
    - 计算机系统概论: CS/index.md
  - C/Cpp:
    - C/Cpp: C_Cpp/index.md
    - 基本结构: C_Cpp/基本结构.md
    - 数据类型: C_Cpp/数据类型.md
  - 数据结构:
    - 数据结构: DataStructures/index.md
    - 概述: DataStructures/概述.md
    - 线性表: DataStructures/线性表.md
    - 栈和队列: DataStructures/栈和队列.md
    - 串、数组和广义表: DataStructures/串、数组和广义表.md
    - 树和二叉树: DataStructures/树和二叉树.md
    - 图: DataStructures/图.md
  - 算法:
    - 算法: Algorithms/index.md
  - Unix:
    - Unix: Unix/index.md
  - Linux:
    - Linux: Linux/index.md
  - FreeBSD:
    - FreeBSD: FreeBSD/index.md
  - Python:
    - Python: Python/index.md
  - OpenGL:
    - OpenGL: OpenGL/index.md
  - English:
    - English: English/index.md
